fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 11cdc8d8201091a19ff1c28f7b7c75c3691954ad
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: no-commit-to-branch
      - id: check-merge-conflict

  - repo: https://github.com/4Catalyzer/fourmat
    rev: master  # or specify a version
    hooks:
      - id: fourmat
